services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: development
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: production 
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '500MB'

  database:
    image: postgres:15.7-bookworm
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 54329:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '500MB'

volumes:
  pgdata:

networks:
  default:
    driver: bridge
    name: finance_virtual_network
