services:
  load-balancer:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    environment:
      NGINX_PORT: 80
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  app1:
    build:
      context: .
    # hostname: app1
    depends_on:
      - database 
    expose:
      - '3000'
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RAILS_ENV: ${RAILS_ENV}
      POSTGRES_DB: ${POSTGRES_DB}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_LOG_LEVEL: warn
      WEB_CONCURRENCY: 2
      RUBY_YJIT_ENABLE: 1
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '0.5GB'

  app2:
    build:
      context: .
    # hostname: app2
    depends_on:
      - database 
    expose:
      - '3000'
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RAILS_ENV: ${RAILS_ENV}
      POSTGRES_DB: ${POSTGRES_DB}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      WEB_CONCURRENCY: 2
      RUBY_YJIT_ENABLE: 1
      RAILS_LOG_LEVEL: warn
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '0.5GB'

  database:
    image: postgres:15.7-bookworm
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./postgresql.conf:/etc/postgresql.conf
    command: postgres -c 'max_connections=500'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '1.5GB'

volumes:
  pgdata:

networks:
  default:
    driver: bridge
    name: finance_virtual_network
