services:
  load-balancer:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    environment:
      NGINX_PORT: 80
    depends_on:
      - app1
      - app2
    # ulimits:
    #   nproc: 1000000
    #   nofile:
    #     soft: 1000000
    #     hard: 1000000 
    # network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  app1:
    # build:
    #   context: .
    #   args:
    #     RAILS_ENV: development 
    image: finance-app
    hostname: app1
    depends_on:
      - database 
    expose:
      - '3000'
    # ports:
    #   - 3000:3000
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_LOG_LEVEL: warn
      WEB_CONCURRENCY: 2
      RUBY_YJIT_ENABLE: 1
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'

  app2:
    # build:
    #   context: .
    #   args:
    #     RAILS_ENV: development
    image: finance-app
    hostname: app1
    depends_on:
      - database 
    expose:
      - '3000'
    # ports:
    #   - 3001:3000
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      WEB_CONCURRENCY: 2
      RUBY_YJIT_ENABLE: 1
      RAILS_LOG_LEVEL: warn
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'

  database:
    image: postgres:15.7-bookworm
    restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./postgresql.conf:/etc/postgresql.conf
    command: postgres -c 'max_connections=500'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '1.5GB'

volumes:
  pgdata:

networks:
  default:
    driver: bridge
    name: finance_virtual_network
